image:
  - Visual Studio 2017

platform:
  - x64

environment:
  global:
    GAMEKIT_SYSTEM_NAME: snake
    GAMEKIT_APPLICATION_PACKAGE: snake
    GAMEKIT_APPLICATION_MAIN_CLASS: snake-game
    GAMEKIT_ARTIFACT: $(GAMEKIT_SYSTEM_NAME)-x86-64-windows.zip
    GAMEKIT_BUILD_DIR: $(TMP)/$(GAMEKIT_SYSTEM_NAME)

skip_non_tags: true

branches:
  only:
    - master
    - "/^v\\d+(\\.\\d+)+$/"


install:
  - set PATH=C:/msys64/usr/bin;%PATH%
  - pacman --noconfirm -Syu
  - pacman --noconfirm -S zip
  - sh -c "curl -L http://bodge.borodust.org/files/install.sh | sh"

build_script:
  - >
    sh -c "$HOME/bin/lisp $HOME/bodge/scripts/build-gamekit-system.lisp
    %GAMEKIT_SYSTEM_NAME% %GAMEKIT_APPLICATION_PACKAGE% %GAMEKIT_APPLICATION_MAIN_CLASS%
    $(cygpath -u '%APPVEYOR_BUILD_FOLDER%')
    $(cygpath -u '%GAMEKIT_BUILD_DIR%')"
  - mv %GAMEKIT_BUILD_DIR%/%GAMEKIT_SYSTEM_NAME%.zip %GAMEKIT_ARTIFACT%

artifacts:
  - path: "%GAMEKIT_ARTIFACT%"
    name: release_archive

deploy:
  provider: GitHub
  auth_token:
    secure: "+JS5PfqKJjiqLG/FWWl4DTyza/fNDDhK75vD99XZaeA6uaviWUgmFWGIe8UwEk5K"
  artifact: release_archive
  force_update: true
